site_name: pgsodium

nav:
  - Getting Started: intro.md
  - Secure Random Numbers: random.md
  - Hashing: hash.md
  - Password Hashing: pwhash.md
  - Message Authentication: hmac.md
  - Authenticated Encryption (AEAD): aead.md
  - Secret Key Encryption: secretbox.md
  - Public Key Encryption: box.md
  - Public Key Signatures: sign.md
  - Key Exchange: kx.md
  - Key Derivation: kdf.md
  - Column Encryption: tce.md

use_directory_urls: false

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - C
    - python
    - pgsql
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
