name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    name: Release on GitHub and PGXN
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: pgxn/pgxn-tools
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
      PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Bundle the Release
      id: bundle
      run: pgxn-bundle
    - name: Release on PGXN
      run: pgxn-release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./${{ steps.bundle.outputs.bundle }}
        generate_release_notes: true
